### ISSUE TITLE
Some Ruby keywords look off in ST4

### ISSUE THREAD

**Issue by kevinsjoberg** [Monokai/monokai-pro-sublime-text#134]
I'm not sure I've seen this in the past but the colouring of some Ruby keywords look off to me.

Here's a screenshot.

<img width="219" alt="Screenshot 2020-12-14 at 18 35 43" src="https://user-images.githubusercontent.com/503025/102115025-3f3eb980-3e3b-11eb-9d88-244d4b4ef155.png">

I would expect `class`/`end` and `def`/`end` to match each other.

Here are the scope names I'm seeing for each keyword.

<img width="345" alt="Screenshot 2020-12-14 at 18 37 20" src="https://user-images.githubusercontent.com/503025/102115237-93499e00-3e3b-11eb-8585-4f6077129321.png">
<img width="385" alt="Screenshot 2020-12-14 at 18 37 27" src="https://user-images.githubusercontent.com/503025/102115239-93e23480-3e3b-11eb-8c8b-0209a5a01be6.png">
<img width="318" alt="Screenshot 2020-12-14 at 18 38 00" src="https://user-images.githubusercontent.com/503025/102115240-947acb00-3e3b-11eb-9258-7f84e9531ecf.png">

**Comment by gobijan** [comment]
Hi, I also noticed it and it is also broken for sublimes own Monokai theme.
They changed a few syntax "things" (not sure what exactly) and I reported this as a bug which they confirmed. They did not change it back via the updates though and other many color themes don't have this problem. So easiest fix would be to go from ruby specific to generic start end keyword declaration? Not sure.

**Comment by Monokai** [comment]
fixed in 1.1.19

**Comment by kevinsjoberg** [comment]
Thank you! 🙏 ❤️

**Comment by kevinsjoberg** [comment]
Turns out it's not completely fixed. `module` keywords are still coloured differently. See attached screenshot.

<img width="237" alt="Screenshot 2021-04-07 at 12 15 28" src="https://user-images.githubusercontent.com/503025/113850612-f2407380-979a-11eb-82d6-b0fb315b38ae.png">

It looks like modules are scoped differently. See attached screenshot.

<img width="323" alt="Screenshot 2021-04-07 at 12 15 54" src="https://user-images.githubusercontent.com/503025/113850683-01272600-979b-11eb-88a9-1e280192aee3.png">

**Comment by alxckn** [comment]
Until this i solved, here is a quick fix (tested on linux):
- Go to `~/.config/sublime-text-3/Installed Packages` (maybe the path will differ a bit with a clean ST4 install -- I upgraded from ST3)
- Open the `Theme - Monokai Pro.sublime-package` file with your archive manager 
- Open the `.sublime-color-scheme` that matches the color scheme you're using (for me it's `Monokai Pro (Filter Machine).sublime-color-scheme`)
- FInd `"name": "ruby specific"` and update the `scope` (add  `, keyword.declaration.namespace.ruby`)
- Save and restart sublime

**Comment by Monokai** [comment]
I've added the the above fix in 1.1.20. Thanks!
